baseurl = "https://decarbdirect.com/" # Configure URL.
title = "Decarb Direct Partners"
theme = "hugo-universal-theme"
themesDir = "themes"
languageCode = "en-us"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

[languages]
	[languages.en]
		languageName = "English"
		contentDir = "content/en"
		weight = 1

    [language.en.params]
        disqusShortname = ""
        googleAnalytics = ""

	[languages.vi]
		languageName = "Vietnamese"
		contentDir = "content/vi"
		weight = 2

	[languages.vi.params]
  		disqusshortname = ""
  		googleanalytics = ""
        viewMorePostLink = "/vi/decarbnews/"
        author = "ddp"
        defaultKeywords = ["decarbonization", "update", "GHG news"]
        mainSections = ["products","resources","decarbnews"]
        defaultDescription = "Cập nhật các bài viết mới nhát liên quan tới thích ứng với biến đổi khí hậu, và phát triển bền vững"
    
        style = "green"

        formspree_action = "https://formspree.io/f/mvoeyrbg"
        contact_form_ajax = false

        enableRecaptchaInContactForm = false
        googleRecaptchaKey = ""

        date_format = "January 2, 2006"

    
        about_us = "<p>Đối tác tin cậy trên hành trình phát triển bền vững</p>"
        contact_url = "/vi/contact"
        address = """<p class="text-uppercase"><strong>Decarb Direct Partners</strong>
                <br>Hà Nội
                <br>Việt Nam
                </p>
                """


    [languages.vi.params.clients]
        enable = true
        title = "Các đối tác"
        subtitle = ""      

    [languages.vi.params.recent_posts]
        enable = true
        title = "Tin tức Decarb"
        subtitle = "Cập nhật các bài viết mới nhát liên quan tới thích ứng với biến đổi khí hậu, và phát triển bền vững"
        hide_summary = false


summaryLength = 70
paginate = 10
pluralizelisttitles = false

[menu]

# Main menu
[[languages.en.menu.main]]
    name       = "Products"
    identifier = "menu.products"
    url        = "/products"
    weight     = 1

[[languages.en.menu.main]]
    name       = "GHG Dashboard"
    url        = "/products/dashboard/"
    weight     = 11
    parent     = "menu.products"

[[languages.en.menu.main]]
    name       = "GHG Analytics"
    url        = "/products/analytics/"
    weight     = 12
    parent     = "menu.products"

[[languages.en.menu.main]]
    name       = "GHG Reporting"
    url        = "/products/reporting/"
    weight     = 13
    parent     = "menu.products"

[[languages.en.menu.main]]
    name       = "Decarbonization Solutions"
    url        = "/products/solutions/"
    weight     = 14
    parent     = "menu.products"

[[languages.en.menu.main]]
    name       = "Resources"
    url        = "/resources"
    identifier = "menu.resources"
    weight     = 2

[[languages.en.menu.main]]
    name       = "Regulatory Updates"
    url        = "/resources/regulatory"
    weight     = 21
    parent     = "menu.resources"

[[languages.en.menu.main]]
    name       = "Decarb Guidelines"
    url        = "/resources/guidelines"
    weight     = 22
    parent     = "menu.resources"

[[languages.en.menu.main]]
    name       = "Case studies"
    url        = "/resources/cases"
    weight     = 23
    parent     = "menu.resources"

[[languages.en.menu.main]]
    name       = "Decarb News"
    url        = "/decarbnews"
    identifier = "menu.decarbnews"
    weight     = 3
    
[[languages.en.menu.main]]
    name       = "About us"
    identifier = "menu.aboutus"
    url        = ""
    weight     = 4

[[languages.en.menu.main]]
    name       = "Mission & Vision"
    url        = "/mission/"
    weight     = 41
    parent     = "menu.aboutus"

[[languages.en.menu.main]]
    name       = "Partnership"
    url        = "/partnership/"
    weight     = 42
    parent     = "menu.aboutus"

[[languages.en.menu.main]]
    name       = "Contact us"
    url        = "/contact/"
    weight     = 43
    parent     = "menu.aboutus"

#Vietnamese main menu

[[languages.vi.menu.main]]
    name       = "Sản phẩm"
    identifier = "menu.products"
    url        = "/vi/products"
    weight     = 1

[[languages.vi.menu.main]]
    name       = "GHG Dashboard"
    url        = "/vi/products/dashboard"
    weight     = 11
    parent     = "menu.products"

[[languages.vi.menu.main]]
    name       = "GHG Analytics"
    url        = "/vi/products/analytics/"
    weight     = 12
    parent     = "menu.products"

[[languages.vi.menu.main]]
    name       = "GHG Reporting"
    url        = "/vi/products/reporting/"
    weight     = 13
    parent     = "menu.products"

[[languages.vi.menu.main]]
    name       = "Decarbonization Solutions"
    url        = "/vi/products/solutions/"
    weight     = 14
    parent     = "menu.products"

[[languages.vi.menu.main]]
    name       = "Thư viện"
    url        = "/vi/resources"
    identifier = "menu.resources"
    weight     = 2

[[languages.vi.menu.main]]
    name       = "Chính sách & quy định mới"
    url        = "/vi/resources/regulatory"
    weight     = 21
    parent     = "menu.resources"

[[languages.vi.menu.main]]
    name       = "Sổ tay hướng dẫn"
    url        = "/vi/resources/guidelines"
    weight     = 22
    parent     = "menu.resources"

[[languages.vi.menu.main]]
    name       = "Case studies"
    url        = "/vi/resources/cases"
    weight     = 23
    parent     = "menu.resources"

[[languages.vi.menu.main]]
    name       = "Decarb News"
    url        = "/vi/decarbnews"
    identifier = "menu.decarbnews"
    weight     = 3
    
[[languages.vi.menu.main]]
    name       = "Về Decarb Direct"
    identifier = "menu.aboutus"
    url        = ""
    weight     = 4

[[languages.vi.menu.main]]
    name       = "Sứ mệnh & Tầm nhìn"
    url        = "/vi/mission/"
    weight     = 41
    parent     = "menu.aboutus"

[[languages.vi.menu.main]]
    name       = "Hợp tác"
    url        = "/vi/partnership/"
    weight     = 42
    parent     = "menu.aboutus"

[[languages.vi.menu.main]]
    name       = "Liên hệ"
    url        = "/vi/contact/"
    weight     = 43
    parent     = "menu.aboutus"


[params]
    viewMorePostLink = "/decarbnews/"
    author = "ddp"
    defaultKeywords = ["decarbonization", "update", "GHG news"]
    mainSections = ["products","resources","decarbnews"]
    defaultDescription = "Latest Updates and Insights in Policy, Decarbonization, Sustainable Development, and Emissions Reduction Efforts"
    
    style = "green"

    formspree_action = "https://formspree.io/f/mvoeyrbg"
    contact_form_ajax = false

    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Your partner in decarbonization journey</p>"
    copyright = "Copyright (c) 2024, Decarb Direct Partners, all rights reserved."

    date_format = "January 2, 2006"

    dropdown_mouse_over = true

    disabled_logo = false
    logo_text = "Decarb Direct Partners"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Decarb Direct Partners</strong>
        <br>Hanoi
        <br>Vietnam
        </p>
      """

[permalinks]
    decarbnews = "/:section/:filename"
    products = "/products/:section/:filename"
    resources = "/resources/:section/:filename"
    "/" = "/:filename"

[params.widgets]
    categories = true
    tags = true
    search = true

[params.features]
    enable = true
    cols = 2

[params.clients]
    enable = true
    title = "Our Clients"
    subtitle = ""  

[params.recent_posts]
    enable = true
    title = "From Decarb News"
    subtitle = "Latest Updates and Insights in Policy, Decarbonization, Sustainable Development, and Emissions Reduction Efforts"
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
  