baseurl = "https://decarbdirect.com/" # Configure URL.
title = "Decarb Direct Partners"
theme = "hugo-universal-theme"
themesDir = "themes"
languageCode = "en-us"

# Site language. Available translations in the theme's `/i18n` directory.
#defaultContentLanguage = "en"

[languages]
	[languages.en]
		languageName = "English"
		contentDir = "content/en"
		weight = 1

	[languages.vi]
		languageName = "Vietnamese"
		contentDir = "content/vi"
		weight = 2

	[languages.vi.params]
  		disqusshortname = ""
  		googleanalytics = ""
        about_us = "<p>Đối tác tin cậy trên hành trình phát triển bền vững</p>"
        contact_url = "/vi/contact"
        address = """<p class="text-uppercase"><strong>Decarb Direct Partners</strong>
        <br>Hà Nội
        <br>Việt Nam
        </p>
        """

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]


# Main menu
[[languages.en.menu.main]]
    name       = "Products"
    identifier = "menu.products"
    url        = "/products"
    weight     = 1

[[languages.en.menu.main]]
    name       = "GHG Dashboard"
    url        = "/products/dashboard"
    weight     = 11
    parent     = "menu.products"

[[languages.en.menu.main]]
    name       = "GHG Analytics"
    url        = "/products/analytics"
    weight     = 12
    parent     = "menu.products"

[[languages.en.menu.main]]
    name       = "GHG Reporting"
    url        = "/products/reporting"
    weight     = 13
    parent     = "menu.products"

[[languages.en.menu.main]]
    name       = "Decarbonization Solutions"
    url        = "/products/solutions"
    weight     = 14
    parent     = "menu.products"

[[languages.en.menu.main]]
    name       = "Resources"
    url        = "/resources"
    identifier = "menu.resources"
    weight     = 2

[[languages.en.menu.main]]
    name       = "Regulatory Updates"
    url        = "/resources/regulatory"
    weight     = 21
    parent     = "menu.resources"

[[languages.en.menu.main]]
    name       = "Decarb Guidelines"
    url        = "/resources/guidelines"
    weight     = 22
    parent     = "menu.resources"

[[languages.en.menu.main]]
    name       = "Case studies"
    url        = "/resources/cases"
    weight     = 23
    parent     = "menu.resources"

[[languages.en.menu.main]]
    name       = "Decarb News"
    url        = "/decarbnews/"
    identifier = "menu.decarbnews"
    weight     = 3
    
[[languages.en.menu.main]]
    name       = "About us"
    identifier = "menu.aboutus"
    url        = "/aboutus/"
    weight     = 4

[[languages.en.menu.main]]
    name       = "Mission & Vision"
    url        = "/aboutus/mission"
    weight     = 41
    parent     = "menu.aboutus"

[[languages.en.menu.main]]
    name       = "Partnership"
    url        = "/aboutus/partnership"
    weight     = 42
    parent     = "menu.aboutus"

[[languages.en.menu.main]]
    name       = "Contact us"
    url        = "/aboutus/contact"
    weight     = 43
    parent     = "menu.aboutus"

#Vietnamese main menu

[[languages.vi.menu.main]]
    name       = "Sản phẩm"
    identifier = "menu.products"
    url        = "/vi/products"
    weight     = 1

[[languages.vi.menu.main]]
    name       = "GHG Dashboard"
    url        = "/vi/products/dashboard"
    weight     = 11
    parent     = "menu.products"

[[languages.vi.menu.main]]
    name       = "GHG Analytics"
    url        = "/vi/products/analytics"
    weight     = 12
    parent     = "menu.products"

[[languages.vi.menu.main]]
    name       = "GHG Reporting"
    url        = "/vi/products/reporting"
    weight     = 13
    parent     = "menu.products"

[[languages.vi.menu.main]]
    name       = "Decarbonization Solutions"
    url        = "/vi/products/solutions"
    weight     = 14
    parent     = "menu.products"

[[languages.vi.menu.main]]
    name       = "Thư viện"
    url        = "/vi/resources"
    identifier = "menu.resources"
    weight     = 2

[[languages.vi.menu.main]]
    name       = "Chính sách & quy định mới"
    url        = "/vi/resources/regulatory"
    weight     = 21
    parent     = "menu.resources"

[[languages.vi.menu.main]]
    name       = "Sổ tay hướng dẫn"
    url        = "/vi/resources/guidelines"
    weight     = 22
    parent     = "menu.resources"

[[languages.vi.menu.main]]
    name       = "Case studies"
    url        = "/vi/resources/cases"
    weight     = 23
    parent     = "menu.resources"

[[languages.vi.menu.main]]
    name       = "Decarb News"
    url        = "/vi/decarbnews/"
    identifier = "menu.decarbnews"
    weight     = 3
    
[[languages.vi.menu.main]]
    name       = "Về Decarb Direct"
    identifier = "menu.aboutus"
    url        = "/vi/aboutus/"
    weight     = 4

[[languages.vi.menu.main]]
    name       = "Sứ mệnh & Tầm nhìn"
    url        = "/vi/aboutus/mission"
    weight     = 41
    parent     = "menu.aboutus"

[[languages.vi.menu.main]]
    name       = "Hợp tác"
    url        = "/vi/aboutus/partnership"
    weight     = 42
    parent     = "menu.aboutus"

[[languages.vi.menu.main]]
    name       = "Liên hệ"
    url        = "/vi/aboutus/contact"
    weight     = 43
    parent     = "menu.aboutus"

[params]
    viewMorePostLink = "/decarbnews/"
    author = "ddp"
    defaultKeywords = ["decarbonization", "update", "GHG news"]
    mainSections = ["decarbnews"]
    defaultDescription = "Latest Updates and Insights in Policy, Decarbonization, Sustainable Development, and Emissions Reduction Efforts"
    
    style = "green"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    # formspree_action = "https://formspree.io/sample/of/endpoint"
    # contact_form_ajax = false

    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Your partner in decarbonization journey</p>"
    copyright = "Copyright (c) 2024, Decarb Direct Partners, all rights reserved."

    date_format = "January 2, 2006"

    dropdown_mouse_over = true

    disabled_logo = false
    logo_text = "Decarb Direct Partners"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Decarb Direct Partners</strong>
        <br>Hanoi
        <br>Vietnam
        </p>
      """

[permalinks]

    decarbnews = "/decarbnews/:year/:month/:day/:filename/"


# Enable or disable top bar with social icons
#[params.topbar]
#    enable = false
#    text = """<p class="hidden-sm hidden-xs">Contact us on +84 912 345 678 or info@decarbdirect.com.</p>
#      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
#      <a href="mailto:info@decarbdirect.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
#      </p>
#      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.features]
    enable = true
    cols = 2

[params.clients]
    enable = true
    title = "Our Clients"
    subtitle = ""  

[languages.vi.params.clients]
    enable = true
    title = "Các đối tác"
    subtitle = ""      

[params.recent_posts]
    enable = true
    title = "From Decarb News"
    subtitle = "Latest Updates and Insights in Policy, Decarbonization, Sustainable Development, and Emissions Reduction Efforts"
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
  